name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        mongodb-version: [4.2]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/bazel-repo
            ~/.cache/bazel-disk
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Write gcp secrets
        run: echo $REMOTE_CACHE_KEYS >> secret-key.json
        env:
          REMOTE_CACHE_KEYS: ${{ secrets.REMOTE_CACHE_KEYS }}

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Install NPM dependencies
        run: |
          yarn install

      - name: Typecheck
        run: yarn typecheck

      - name: Run Buldifier lint
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" run --build_tag_filters=manual //:buildifier.lint

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # This is probably not necessary to run
      # - name: Build
      #   run: |
      #     echo BASE_URL=$BASE_URL >> src/trainingjournal/.env
      #     "${GITHUB_WORKSPACE}/bin/bazel" build '...'
      #   env:
      #     BASE_URL: ${{ secrets.BASE_URL }}

      - name: Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test '...'
